env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - plugin:perfectionist/recommended-alphabetical
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - fp
  - perfectionist
rules:
  no-console: off
  import/extensions: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
