env:
  browser: true
  es2021: true
  jest: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - fp
rules:
  no-console: off
  import/extensions: off
  fp/no-mutating-methods: ["error", {"allowedObjects": ["_"]}]
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
